Repository abobija/esp-idf-rc522, pull requests merged in 2023-11, with the labels that each got.

#20 don't dereference and free buffer if there have been some kind of errors while reading
  rc522.c
Labels: bug

#28 Return `esp_err_t` from read function
  rc522.c
Labels: enhancement

#24 Change logic of freeing of SPI bus to when not initialized by user.
  rc522.c
Labels: bug

#29 Return `esp_err_t` from all functions
  rc522.c
  rc522.h
Labels: enhancement

#30 Memory allocation checks
  rc522.c
Labels: enhancement

#31 Improved overall resilience
  idf_component.yml
  rc522.c
  rc522.h
Labels: enhancement

#32 v2.5.0: Improved system resilience and memory management
  idf_component.yml
  rc522.c
  rc522.h
Labels: bug, enhancement

#33 Refactor: rename guard macros and organize files
  CMakeLists.txt
  idf_component.yml
  include/guards.h
  include/rc522.h
  src/rc522.c
Labels: enhancement

#34 Defined registers
  include/rc522_registers.h
  src/rc522.c
Labels: enhancement
